apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipelinerun-object-results-
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskSpec:
          results:
            - name: object-results
              type: object
              description: The object results
              properties:
                url:
                  type: string
                digest:
                  type: string
          steps:
            - name: write-object
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                set -x
                echo -n "{\"url\":\"abc.dev/sampler\",\"digest\":\"19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791\"}" | tee $(results.object-results.path)
                cat $(results.object-results.path)
                ls -al $(results.object-results.path)
      - name: task2
        params:
          - name: whole-object
            value: "$(tasks.task1.results.object-results[*])"
          - name: object-url
            value: "$(tasks.task1.results.object-results.url)"
        taskSpec:
          params:
            - name: object-url
              type: string
            - name: whole-object
              type: object
              properties:
                url:
                  type: string
                digest:
                  type: string
          steps:
            - name: validate-object-url
              image: bash:latest
              args: ["$(params.whole-object.url)"]
              script: |
                set -x
                if [[ $1 != "abc.dev/sampler" ]]; then
                    echo "failed to validate the one and only argument of the script"
                    echo "Want: abc.dev/sampler, Got: $1"
                  exit 1
                else
                  echo "validate the object-url successfully"
                fi
            - name: validate-whole-object
              image: ubuntu
              script: |
                #!/bin/bash
                set -x
                EXPECTED_url=abc.dev/sampler
                EXPECTED_digest="19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791"

                if [[ $(params.whole-object.url) != ${EXPECTED_url} ]]; then
                    echo "failed to validate the object"
                    echo "Want: ${EXPECTED_url}, Got: $(params.whole-object.url)"
                  exit 1
                else
                  echo "validate the object url successfully"
                fi

                if [[ $(params.whole-object.digest) != ${EXPECTED_digest} ]]; then
                    echo "failed to validate the object"
                    echo "Want: ${EXPECTED_digest}, Got: $(params.whole-object.digest)"
                  exit 1
                else
                  echo "validate the object digest successfully"
                fi

# ---
# $ kubectl logs  pipelinerun-object-results-qnk8x-task1-pod
# Defaulted container "step-write-object" out of: step-write-object, prepare (init), place-scripts (init)
# + echo -n '{"url":"abc.dev/sampler","digest":"19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791"}'
# + tee /tekton/results/object-results
# {"url":"abc.dev/sampler","digest":"19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791"}

# + cat /tekton/results/object-results
# {"url":"abc.dev/sampler","digest":"19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791"}

# + ls -al /tekton/results/object-results
# -rw-r--r--    1 root     root           101 Apr 30 13:24 /tekton/results/object-results
# $

# $ kubectl logs pipelinerun-object-results-qnk8x-task2-pod -c step-validate-object-url
# + '[[' abc.dev/sampler '!=' abc.dev/sampler ]]
# + echo 'validate the object-url successfully'
# validate the object-url successfully
# $

# $ kubectl logs pipelinerun-object-results-qnk8x-task2-pod -c step-validate-whole-object
# + EXPECTED_url=abc.dev/sampler
# + EXPECTED_digest=19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
# + [[ abc.dev/sampler != abc.dev/sampler ]]
# + echo 'validate the object url successfully'
# validate the object url successfully
# + [[ 19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791 != 19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791 ]]
# + echo 'validate the object digest successfully'
# validate the object digest successfully
# $
