apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  params:
    - name: username
      type: string
  tasks:
    - name: hello
      taskRef:
        name: hello
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbye
      params:
        - name: username
          value: $(params.username)
# ---
# $ kubectl get pods -o wide
# NAME                            READY   STATUS      RESTARTS   AGE   IP           NODE              NOMINATED NODE   READINESS GATES
# hello-goodbye-run-goodbye-pod   0/1     Completed   0          18s   10.3.0.134   192.168.137.27    <none>           <none>
# hello-goodbye-run-hello-pod     0/1     Completed   0          27s   10.3.0.133   192.168.141.101   <none>           <none>
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"PipelineRun","metadata":{"annotations":{},"name":"hello-goodbye-run","namespace":"default"},"spec":{"params":[{"name":"username","value":"Tekton"}],"pipelineRef":{"name":"hello-goodbye"}}}
    pipeline.tekton.dev/release: d714545
    tekton.dev/ready: READY
  creationTimestamp: "2024-04-30T10:23:03Z"
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/memberOf: tasks
    tekton.dev/pipeline: hello-goodbye
    tekton.dev/pipelineRun: hello-goodbye-run
    tekton.dev/pipelineTask: goodbye
    tekton.dev/task: goodbye
    tekton.dev/taskRun: hello-goodbye-run-goodbye
  name: hello-goodbye-run-goodbye-pod
  namespace: default
  ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: TaskRun
      name: hello-goodbye-run-goodbye
      uid: 1bc4a032-8ac9-4d4b-8bea-535f877b7759
  resourceVersion: "637894"
  uid: a6d9426c-c212-459b-a8a3-b76675119255
spec:
  activeDeadlineSeconds: 5400
  containers:
    - args:
        - -wait_file
        - /tekton/downward/ready
        - -wait_file_content
        - -post_file
        - /tekton/run/0/out
        - -termination_path
        - /tekton/termination
        - -step_metadata_dir
        - /tekton/run/0/status
        - -entrypoint
        - /tekton/scripts/script-0-xhp6n
        - --
      command:
        - /tekton/bin/entrypoint
      image: ubuntu
      imagePullPolicy: Always
      name: step-goodbye
      resources: {}
      terminationMessagePath: /tekton/termination
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /tekton/scripts
          name: tekton-internal-scripts
          readOnly: true
        - mountPath: /tekton/downward
          name: tekton-internal-downward
          readOnly: true
        - mountPath: /tekton/creds
          name: tekton-creds-init-home-0
        - mountPath: /tekton/run/0
          name: tekton-internal-run-0
        - mountPath: /tekton/bin
          name: tekton-internal-bin
          readOnly: true
        - mountPath: /workspace
          name: tekton-internal-workspace
        - mountPath: /tekton/home
          name: tekton-internal-home
        - mountPath: /tekton/results
          name: tekton-internal-results
        - mountPath: /tekton/steps
          name: tekton-internal-steps
          readOnly: true
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-fmxzc
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
    - command:
        - /ko-app/entrypoint
        - init
        - /ko-app/entrypoint
        - /tekton/bin/entrypoint
        - step-goodbye
      image: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint:v0.57.0
      imagePullPolicy: IfNotPresent
      name: prepare
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /tekton/bin
          name: tekton-internal-bin
        - mountPath: /tekton/steps
          name: tekton-internal-steps
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-fmxzc
          readOnly: true
      workingDir: /
    - args:
        - -c
        - |
          scriptfile="/tekton/scripts/script-0-xhp6n"
          touch ${scriptfile} && chmod +x ${scriptfile}
          cat > ${scriptfile} << '_EOF_'
          IyEvYmluL2Jhc2gKZWNobyAiR29vZGJ5ZSBUZWt0b24hIgo=
          _EOF_
          /tekton/bin/entrypoint decode-script "${scriptfile}"
      command:
        - sh
      image: ghcr.io/lanzhiwang/chainguard/busybox:v1.0.0
      imagePullPolicy: IfNotPresent
      name: place-scripts
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /tekton/scripts
          name: tekton-internal-scripts
        - mountPath: /tekton/bin
          name: tekton-internal-bin
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-fmxzc
          readOnly: true
  nodeName: 192.168.137.27
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 30
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 30
  volumes:
    - emptyDir: {}
      name: tekton-internal-workspace
    - emptyDir: {}
      name: tekton-internal-home
    - emptyDir: {}
      name: tekton-internal-results
    - emptyDir: {}
      name: tekton-internal-steps
    - emptyDir: {}
      name: tekton-internal-scripts
    - emptyDir: {}
      name: tekton-internal-bin
    - downwardAPI:
        defaultMode: 420
        items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['tekton.dev/ready']
            path: ready
      name: tekton-internal-downward
    - emptyDir:
        medium: Memory
      name: tekton-creds-init-home-0
    - emptyDir: {}
      name: tekton-internal-run-0
    - name: kube-api-access-fmxzc
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
