apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: array-with-default-
spec:
  params:
    - name: array-to-echo
      value:
        - "foo"
        - "bar"
  taskSpec:
    params:
      - name: array-to-echo
        type: array
      - name: another-array-to-echo
        type: array
        default:
          - "foo-default"
          - "bar-default"
      - name: string-to-echo
        type: string
        default: "baz"
    steps:
      # this step should echo "foo bar foo-default bar-default baz"
      - name: echo-params
        image: bash:3.2
        args:
          [
            "echo",
            "$(params.array-to-echo[*])",
            "$(params.another-array-to-echo[*])",
            "$(params.string-to-echo)",
          ]
# ---
# $ kubectl logs array-with-default-6cqdg-pod
# Defaulted container "step-echo-params" out of: step-echo-params, prepare (init)
# foo bar foo-default bar-default baz

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   annotations:
#     pipeline.tekton.dev/release: d714545
#     tekton.dev/ready: READY
#   creationTimestamp: "2024-04-30T02:46:36Z"
#   labels:
#     app.kubernetes.io/managed-by: tekton-pipelines
#     tekton.dev/taskRun: array-with-default-6cqdg
#   name: array-with-default-6cqdg-pod
#   namespace: default
#   ownerReferences:
#   - apiVersion: tekton.dev/v1
#     blockOwnerDeletion: true
#     controller: true
#     kind: TaskRun
#     name: array-with-default-6cqdg
#     uid: f88a11ee-fd2f-4c49-8b6d-8101e6c5fa5f
#   resourceVersion: "423559"
#   uid: e8924716-28e7-44e0-8fa2-56ac943cc0da
# spec:
#   activeDeadlineSeconds: 5400
#   containers:
#   - args:
#     - -wait_file
#     - /tekton/downward/ready
#     - -wait_file_content
#     - -post_file
#     - /tekton/run/0/out
#     - -termination_path
#     - /tekton/termination
#     - -step_metadata_dir
#     - /tekton/run/0/status
#     - --
#     - echo
#     - foo
#     - bar
#     - foo-default
#     - bar-default
#     - baz
#     command:
#     - /tekton/bin/entrypoint
#     env:
#     - name: TEKTON_PLATFORM_COMMANDS
#       value: '{"linux/386":["docker-entrypoint.sh"],"linux/amd64":["docker-entrypoint.sh"],"linux/arm/v6":["docker-entrypoint.sh"],"linux/arm/v7":["docker-entrypoint.sh"],"linux/arm64/v8":["docker-entrypoint.sh"],"linux/ppc64le":["docker-entrypoint.sh"],"linux/s390x":["docker-entrypoint.sh"]}'
#     image: index.docker.io/library/bash@sha256:b89a5501ba42e3acac66dc43632b97378fba5f3b2bb4ec542021f4454a2d7959
#     imagePullPolicy: IfNotPresent
#     name: step-echo-params
#     resources: {}
#     terminationMessagePath: /tekton/termination
#     terminationMessagePolicy: File
#     volumeMounts:
#     - mountPath: /tekton/downward
#       name: tekton-internal-downward
#       readOnly: true
#     - mountPath: /tekton/creds
#       name: tekton-creds-init-home-0
#     - mountPath: /tekton/run/0
#       name: tekton-internal-run-0
#     - mountPath: /tekton/bin
#       name: tekton-internal-bin
#       readOnly: true
#     - mountPath: /workspace
#       name: tekton-internal-workspace
#     - mountPath: /tekton/home
#       name: tekton-internal-home
#     - mountPath: /tekton/results
#       name: tekton-internal-results
#     - mountPath: /tekton/steps
#       name: tekton-internal-steps
#       readOnly: true
#     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#       name: kube-api-access-7brgr
#       readOnly: true
#   dnsPolicy: ClusterFirst
#   enableServiceLinks: true
#   initContainers:
#   - command:
#     - /ko-app/entrypoint
#     - init
#     - /ko-app/entrypoint
#     - /tekton/bin/entrypoint
#     - step-echo-params
#     image: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint:v0.57.0
#     imagePullPolicy: IfNotPresent
#     name: prepare
#     resources: {}
#     terminationMessagePath: /dev/termination-log
#     terminationMessagePolicy: File
#     volumeMounts:
#     - mountPath: /tekton/bin
#       name: tekton-internal-bin
#     - mountPath: /tekton/steps
#       name: tekton-internal-steps
#     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#       name: kube-api-access-7brgr
#       readOnly: true
#     workingDir: /
#   nodeName: 192.168.137.27
#   preemptionPolicy: PreemptLowerPriority
#   priority: 0
#   restartPolicy: Never
#   schedulerName: default-scheduler
#   securityContext: {}
#   serviceAccount: default
#   serviceAccountName: default
#   terminationGracePeriodSeconds: 30
#   tolerations:
#   - effect: NoExecute
#     key: node.kubernetes.io/not-ready
#     operator: Exists
#     tolerationSeconds: 30
#   - effect: NoExecute
#     key: node.kubernetes.io/unreachable
#     operator: Exists
#     tolerationSeconds: 30
#   volumes:
#   - emptyDir: {}
#     name: tekton-internal-workspace
#   - emptyDir: {}
#     name: tekton-internal-home
#   - emptyDir: {}
#     name: tekton-internal-results
#   - emptyDir: {}
#     name: tekton-internal-steps
#   - emptyDir: {}
#     name: tekton-internal-bin
#   - downwardAPI:
#       defaultMode: 420
#       items:
#       - fieldRef:
#           apiVersion: v1
#           fieldPath: metadata.annotations['tekton.dev/ready']
#         path: ready
#     name: tekton-internal-downward
#   - emptyDir:
#       medium: Memory
#     name: tekton-creds-init-home-0
#   - emptyDir: {}
#     name: tekton-internal-run-0
#   - name: kube-api-access-7brgr
#     projected:
#       defaultMode: 420
#       sources:
#       - serviceAccountToken:
#           expirationSeconds: 3607
#           path: token
#       - configMap:
#           items:
#           - key: ca.crt
#             path: ca.crt
#           name: kube-root-ca.crt
#       - downwardAPI:
#           items:
#           - fieldRef:
#               apiVersion: v1
#               fieldPath: metadata.namespace
#             path: namespace
# status:
#   conditions:
#   - lastProbeTime: null
#     lastTransitionTime: "2024-04-30T02:46:38Z"
#     reason: PodCompleted
#     status: "True"
#     type: Initialized
#   - lastProbeTime: null
#     lastTransitionTime: "2024-04-30T02:46:49Z"
#     reason: PodCompleted
#     status: "False"
#     type: Ready
#   - lastProbeTime: null
#     lastTransitionTime: "2024-04-30T02:46:49Z"
#     reason: PodCompleted
#     status: "False"
#     type: ContainersReady
#   - lastProbeTime: null
#     lastTransitionTime: "2024-04-30T02:46:36Z"
#     status: "True"
#     type: PodScheduled
#   containerStatuses:
#   - containerID: containerd://bde0de9c8e844dd437ea56f99baf23b0791e292ce6cbf2f127590d81d5a5db3f
#     image: sha256:bde9ed40615147017b4bb897e11056d42a69c69fae7ac11b47195d25de2ff9f1
#     imageID: docker.io/library/bash@sha256:b89a5501ba42e3acac66dc43632b97378fba5f3b2bb4ec542021f4454a2d7959
#     lastState: {}
#     name: step-echo-params
#     ready: false
#     restartCount: 0
#     started: false
#     state:
#       terminated:
#         containerID: containerd://bde0de9c8e844dd437ea56f99baf23b0791e292ce6cbf2f127590d81d5a5db3f
#         exitCode: 0
#         finishedAt: "2024-04-30T02:46:49Z"
#         message: '[{"key":"StartedAt","value":"2024-04-30T02:46:49.550Z","type":3}]'
#         reason: Completed
#         startedAt: "2024-04-30T02:46:47Z"
#   hostIP: 192.168.137.27
#   initContainerStatuses:
#   - containerID: containerd://a0b63686df40fcbbade0c20e6a577ecd9c91f7b39c3d9a0bebc858b2a02a0f3a
#     image: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint:v0.57.0
#     imageID: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint@sha256:2aedd9b42d8ba49bf88de4bb6e789088ce3f6ac34cd8303dad18c2608e8f4008
#     lastState: {}
#     name: prepare
#     ready: true
#     restartCount: 0
#     state:
#       terminated:
#         containerID: containerd://a0b63686df40fcbbade0c20e6a577ecd9c91f7b39c3d9a0bebc858b2a02a0f3a
#         exitCode: 0
#         finishedAt: "2024-04-30T02:46:38Z"
#         reason: Completed
#         startedAt: "2024-04-30T02:46:37Z"
#   phase: Succeeded
#   podIP: 10.3.0.105
#   podIPs:
#   - ip: 10.3.0.105
#   qosClass: BestEffort
#   startTime: "2024-04-30T02:46:36Z"

