apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: custom-env-
spec:
  taskSpec:
    steps:
      - image: ubuntu
        script: |
          #!/usr/bin/env bash
          [[ $MY_VAR1 == foo ]]
        env:
          - name: MY_VAR1
            value: foo
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   annotations:
#     pipeline.tekton.dev/release: d714545
#     tekton.dev/ready: READY
#   creationTimestamp: "2024-04-30T03:09:01Z"
#   labels:
#     app.kubernetes.io/managed-by: tekton-pipelines
#     tekton.dev/taskRun: custom-env-r64j2
#   name: custom-env-r64j2-pod
#   namespace: default
#   ownerReferences:
#     - apiVersion: tekton.dev/v1
#       blockOwnerDeletion: true
#       controller: true
#       kind: TaskRun
#       name: custom-env-r64j2
#       uid: 25f9d740-2403-4927-9714-0cfeb299a0cc
#   resourceVersion: "434032"
#   uid: 6975f753-2fcf-479a-889b-355fc9d05368
# spec:
#   activeDeadlineSeconds: 5400
#   containers:
#     - args:
#         - -wait_file
#         - /tekton/downward/ready
#         - -wait_file_content
#         - -post_file
#         - /tekton/run/0/out
#         - -termination_path
#         - /tekton/termination
#         - -step_metadata_dir
#         - /tekton/run/0/status
#         - -entrypoint
#         - /tekton/scripts/script-0-8t54b
#         - --
#       command:
#         - /tekton/bin/entrypoint
#       env:
#         - name: MY_VAR1
#           value: foo
#       image: ubuntu
#       imagePullPolicy: Always
#       name: step-unnamed-0
#       resources: {}
#       terminationMessagePath: /tekton/termination
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /tekton/scripts
#           name: tekton-internal-scripts
#           readOnly: true
#         - mountPath: /tekton/downward
#           name: tekton-internal-downward
#           readOnly: true
#         - mountPath: /tekton/creds
#           name: tekton-creds-init-home-0
#         - mountPath: /tekton/run/0
#           name: tekton-internal-run-0
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#           readOnly: true
#         - mountPath: /workspace
#           name: tekton-internal-workspace
#         - mountPath: /tekton/home
#           name: tekton-internal-home
#         - mountPath: /tekton/results
#           name: tekton-internal-results
#         - mountPath: /tekton/steps
#           name: tekton-internal-steps
#           readOnly: true
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-x295j
#           readOnly: true
#   dnsPolicy: ClusterFirst
#   enableServiceLinks: true
#   initContainers:
#     - command:
#         - /ko-app/entrypoint
#         - init
#         - /ko-app/entrypoint
#         - /tekton/bin/entrypoint
#         - step-unnamed-0
#       image: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint:v0.57.0
#       imagePullPolicy: IfNotPresent
#       name: prepare
#       resources: {}
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#         - mountPath: /tekton/steps
#           name: tekton-internal-steps
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-x295j
#           readOnly: true
#       workingDir: /
#     - args:
#         - -c
#         - |
#           scriptfile="/tekton/scripts/script-0-8t54b"
#           touch ${scriptfile} && chmod +x ${scriptfile}
#           cat > ${scriptfile} << '_EOF_'
#           IyEvdXNyL2Jpbi9lbnYgYmFzaApbWyAkTVlfVkFSMSA9PSBmb28gXV0K
#           _EOF_
#           /tekton/bin/entrypoint decode-script "${scriptfile}"
#       command:
#         - sh
#       image: ghcr.io/lanzhiwang/chainguard/busybox:v1.0.0
#       imagePullPolicy: IfNotPresent
#       name: place-scripts
#       resources: {}
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /tekton/scripts
#           name: tekton-internal-scripts
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-x295j
#           readOnly: true
#   nodeName: 192.168.137.27
#   preemptionPolicy: PreemptLowerPriority
#   priority: 0
#   restartPolicy: Never
#   schedulerName: default-scheduler
#   securityContext: {}
#   serviceAccount: default
#   serviceAccountName: default
#   terminationGracePeriodSeconds: 30
#   tolerations:
#     - effect: NoExecute
#       key: node.kubernetes.io/not-ready
#       operator: Exists
#       tolerationSeconds: 30
#     - effect: NoExecute
#       key: node.kubernetes.io/unreachable
#       operator: Exists
#       tolerationSeconds: 30
#   volumes:
#     - emptyDir: {}
#       name: tekton-internal-workspace
#     - emptyDir: {}
#       name: tekton-internal-home
#     - emptyDir: {}
#       name: tekton-internal-results
#     - emptyDir: {}
#       name: tekton-internal-steps
#     - emptyDir: {}
#       name: tekton-internal-scripts
#     - emptyDir: {}
#       name: tekton-internal-bin
#     - downwardAPI:
#         defaultMode: 420
#         items:
#           - fieldRef:
#               apiVersion: v1
#               fieldPath: metadata.annotations['tekton.dev/ready']
#             path: ready
#       name: tekton-internal-downward
#     - emptyDir:
#         medium: Memory
#       name: tekton-creds-init-home-0
#     - emptyDir: {}
#       name: tekton-internal-run-0
#     - name: kube-api-access-x295j
#       projected:
#         defaultMode: 420
#         sources:
#           - serviceAccountToken:
#               expirationSeconds: 3607
#               path: token
#           - configMap:
#               items:
#                 - key: ca.crt
#                   path: ca.crt
#               name: kube-root-ca.crt
#           - downwardAPI:
#               items:
#                 - fieldRef:
#                     apiVersion: v1
#                     fieldPath: metadata.namespace
#                   path: namespace
# status:
#   conditions:
#     - lastProbeTime: null
#       lastTransitionTime: "2024-04-30T03:09:04Z"
#       reason: PodCompleted
#       status: "True"
#       type: Initialized
#     - lastProbeTime: null
#       lastTransitionTime: "2024-04-30T03:09:10Z"
#       reason: PodCompleted
#       status: "False"
#       type: Ready
#     - lastProbeTime: null
#       lastTransitionTime: "2024-04-30T03:09:10Z"
#       reason: PodCompleted
#       status: "False"
#       type: ContainersReady
#     - lastProbeTime: null
#       lastTransitionTime: "2024-04-30T03:09:01Z"
#       status: "True"
#       type: PodScheduled
#   containerStatuses:
#     - containerID: containerd://086be0a4593599d2ab2a8b8613fb0e6644a46679ef832cbdabd60844656fe309
#       image: docker.io/library/ubuntu:latest
#       imageID: docker.io/library/ubuntu@sha256:562456a05a0dbd62a671c1854868862a4687bf979a96d48ae8e766642cd911e8
#       lastState: {}
#       name: step-unnamed-0
#       ready: false
#       restartCount: 0
#       started: false
#       state:
#         terminated:
#           containerID: containerd://086be0a4593599d2ab2a8b8613fb0e6644a46679ef832cbdabd60844656fe309
#           exitCode: 0
#           finishedAt: "2024-04-30T03:09:08Z"
#           message: '[{"key":"StartedAt","value":"2024-04-30T03:09:08.970Z","type":3}]'
#           reason: Completed
#           startedAt: "2024-04-30T03:09:06Z"
#   hostIP: 192.168.137.27
#   initContainerStatuses:
#     - containerID: containerd://07bb0745d38a8d252f9337b1bd9b602e0f6116dc00acdf2af66024794b2cbc28
#       image: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint:v0.57.0
#       imageID: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint@sha256:2aedd9b42d8ba49bf88de4bb6e789088ce3f6ac34cd8303dad18c2608e8f4008
#       lastState: {}
#       name: prepare
#       ready: true
#       restartCount: 0
#       state:
#         terminated:
#           containerID: containerd://07bb0745d38a8d252f9337b1bd9b602e0f6116dc00acdf2af66024794b2cbc28
#           exitCode: 0
#           finishedAt: "2024-04-30T03:09:02Z"
#           reason: Completed
#           startedAt: "2024-04-30T03:09:02Z"
#     - containerID: containerd://6951fc9687a545f1d26916e2d947e113d7e2737dd9b1e72028d47d8781e653f7
#       image: ghcr.io/lanzhiwang/chainguard/busybox:v1.0.0
#       imageID: ghcr.io/lanzhiwang/chainguard/busybox@sha256:48604a9f16721131879bbbbb05f28df84f82d3a83ff11fe523a293f485cd3591
#       lastState: {}
#       name: place-scripts
#       ready: true
#       restartCount: 0
#       state:
#         terminated:
#           containerID: containerd://6951fc9687a545f1d26916e2d947e113d7e2737dd9b1e72028d47d8781e653f7
#           exitCode: 0
#           finishedAt: "2024-04-30T03:09:03Z"
#           reason: Completed
#           startedAt: "2024-04-30T03:09:03Z"
#   phase: Succeeded
#   podIP: 10.3.0.107
#   podIPs:
#     - ip: 10.3.0.107
#   qosClass: BestEffort
#   startTime: "2024-04-30T03:09:01Z"
