apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: sidecar-ready-
spec:
  taskSpec:
    sidecars:
      - name: slow-sidecar
        image: ubuntu
        script: |
          echo "hello from sidecar" > /shared/message
        volumeMounts:
          - name: shared
            mountPath: /shared

    steps:
      - name: check-ready
        image: ubuntu
        script: cat /shared/message
        volumeMounts:
          - name: shared
            mountPath: /shared

    # Sidecars don't have /workspace mounted by default, so we have to define
    # our own shared volume.
    volumes:
      - name: shared
        emptyDir: {}
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   annotations:
#     pipeline.tekton.dev/release: d714545
#     tekton.dev/ready: READY
#   labels:
#     app.kubernetes.io/managed-by: tekton-pipelines
#     tekton.dev/taskRun: sidecar-ready-nw88v
#   name: sidecar-ready-nw88v-pod
#   namespace: default
#   ownerReferences:
#     - apiVersion: tekton.dev/v1
#       blockOwnerDeletion: true
#       controller: true
#       kind: TaskRun
#       name: sidecar-ready-nw88v
#       uid: bf8a1cc9-42da-4a2e-89c2-92d61021b363
# spec:
#   activeDeadlineSeconds: 5400
#   containers:
#     - args:
#         - -wait_file
#         - /tekton/downward/ready
#         - -wait_file_content
#         - -post_file
#         - /tekton/run/0/out
#         - -termination_path
#         - /tekton/termination
#         - -step_metadata_dir
#         - /tekton/run/0/status
#         - -entrypoint
#         - /tekton/scripts/script-0-599m9
#         - --
#       command:
#         - /tekton/bin/entrypoint
#       image: ubuntu
#       imagePullPolicy: Always
#       name: step-check-ready
#       resources: {}
#       terminationMessagePath: /tekton/termination
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /shared
#           name: shared
#         - mountPath: /tekton/scripts
#           name: tekton-internal-scripts
#           readOnly: true
#         - mountPath: /tekton/downward
#           name: tekton-internal-downward
#           readOnly: true
#         - mountPath: /tekton/creds
#           name: tekton-creds-init-home-0
#         - mountPath: /tekton/run/0
#           name: tekton-internal-run-0
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#           readOnly: true
#         - mountPath: /workspace
#           name: tekton-internal-workspace
#         - mountPath: /tekton/home
#           name: tekton-internal-home
#         - mountPath: /tekton/results
#           name: tekton-internal-results
#         - mountPath: /tekton/steps
#           name: tekton-internal-steps
#           readOnly: true
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-d7kvp
#           readOnly: true
#     - command:
#         - /tekton/scripts/sidecar-script-0-qrpkc
#       image: ubuntu
#       imagePullPolicy: Always
#       name: sidecar-slow-sidecar
#       resources: {}
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /shared
#           name: shared
#         - mountPath: /tekton/scripts
#           name: tekton-internal-scripts
#           readOnly: true
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-d7kvp
#           readOnly: true
#   dnsPolicy: ClusterFirst
#   enableServiceLinks: true
#   initContainers:
#     - command:
#         - /ko-app/entrypoint
#         - init
#         - /ko-app/entrypoint
#         - /tekton/bin/entrypoint
#         - step-check-ready
#       image: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint:v0.57.0
#       imagePullPolicy: IfNotPresent
#       name: prepare
#       resources: {}
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#         - mountPath: /tekton/steps
#           name: tekton-internal-steps
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-d7kvp
#           readOnly: true
#       workingDir: /
#     - args:
#         - -c
#         - |
#           scriptfile="/tekton/scripts/script-0-599m9"
#           touch ${scriptfile} && chmod +x ${scriptfile}
#           cat > ${scriptfile} << '_EOF_'
#           IyEvYmluL3NoCnNldCAtZQpjYXQgL3NoYXJlZC9tZXNzYWdl
#           _EOF_
#           /tekton/bin/entrypoint decode-script "${scriptfile}"
#           scriptfile="/tekton/scripts/sidecar-script-0-qrpkc"
#           touch ${scriptfile} && chmod +x ${scriptfile}
#           cat > ${scriptfile} << '_EOF_'
#           IyEvYmluL3NoCnNldCAtZQplY2hvICJoZWxsbyBmcm9tIHNpZGVjYXIiID4gL3NoYXJlZC9tZXNzYWdlCg==
#           _EOF_
#           /tekton/bin/entrypoint decode-script "${scriptfile}"
#       command:
#         - sh
#       image: ghcr.io/lanzhiwang/chainguard/busybox:v1.0.0
#       imagePullPolicy: IfNotPresent
#       name: place-scripts
#       resources: {}
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /tekton/scripts
#           name: tekton-internal-scripts
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-d7kvp
#           readOnly: true
#   nodeName: 192.168.138.249
#   preemptionPolicy: PreemptLowerPriority
#   priority: 0
#   restartPolicy: Never
#   schedulerName: default-scheduler
#   securityContext: {}
#   serviceAccount: default
#   serviceAccountName: default
#   terminationGracePeriodSeconds: 30
#   tolerations:
#     - effect: NoExecute
#       key: node.kubernetes.io/not-ready
#       operator: Exists
#       tolerationSeconds: 30
#     - effect: NoExecute
#       key: node.kubernetes.io/unreachable
#       operator: Exists
#       tolerationSeconds: 30
#   volumes:
#     - emptyDir: {}
#       name: tekton-internal-workspace
#     - emptyDir: {}
#       name: tekton-internal-home
#     - emptyDir: {}
#       name: tekton-internal-results
#     - emptyDir: {}
#       name: tekton-internal-steps
#     - emptyDir: {}
#       name: tekton-internal-scripts
#     - emptyDir: {}
#       name: tekton-internal-bin
#     - downwardAPI:
#         defaultMode: 420
#         items:
#           - fieldRef:
#               apiVersion: v1
#               fieldPath: metadata.annotations['tekton.dev/ready']
#             path: ready
#       name: tekton-internal-downward
#     - emptyDir:
#         medium: Memory
#       name: tekton-creds-init-home-0
#     - emptyDir: {}
#       name: tekton-internal-run-0
#     - emptyDir: {}
#       name: shared
#     - name: kube-api-access-d7kvp
#       projected:
#         defaultMode: 420
#         sources:
#           - serviceAccountToken:
#               expirationSeconds: 3607
#               path: token
#           - configMap:
#               items:
#                 - key: ca.crt
#                   path: ca.crt
#               name: kube-root-ca.crt
#           - downwardAPI:
#               items:
#                 - fieldRef:
#                     apiVersion: v1
#                     fieldPath: metadata.namespace
#                   path: namespace

