apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: task-with-workspace-run-
spec:
  taskSpec:
    steps:
      - name: list-files
        image: alpine
        script: |
          set -x
          apk add tree
          tree -a /tekton
          tree -a /workspace
          ls $(workspaces.read-allowed.path)
          tree -a /tekton
          tree -a /workspace
    workspaces:
      - name: read-allowed
  workspaces:
    - name: read-allowed
      volumeClaimTemplate:
        metadata:
          name: pvc
        spec:
          storageClassName: sc-topolvm
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
# ---
# $ kubectl logs -f task-with-workspace-run-pqjfb-pod
# Defaulted container "step-list-files" out of: step-list-files, prepare (init), place-scripts (init)

# + apk add tree
# fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
# fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
# WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.19/community: BAD signature
# (1/1) Installing tree (2.1.1-r0)
# Executing busybox-1.36.1-r15.trigger
# OK: 7 MiB in 16 packages

# + tree -a /tekton
# /tekton
# ├── bin
# │   └── entrypoint
# ├── creds
# ├── downward
# │   ├── ..2024_04_30_09_51_50.1272065217
# │   │   └── ready
# │   ├── ..data -> ..2024_04_30_09_51_50.1272065217
# │   └── ready -> ..data/ready
# ├── home
# ├── results
# ├── run
# │   └── 0
# │       └── status
# │           └── results
# ├── scripts
# │   └── script-0-grng7
# ├── steps
# │   ├── 0 -> /tekton/run/0/status
# │   └── step-list-files -> /tekton/run/0/status
# └── termination

# 16 directories, 5 files

# + tree -a /workspace
# /workspace
# └── read-allowed

# 2 directories, 0 files

# + ls /workspace/read-allowed

# + tree -a /tekton
# /tekton
# ├── bin
# │   └── entrypoint
# ├── creds
# ├── downward
# │   ├── ..2024_04_30_09_51_50.1272065217
# │   │   └── ready
# │   ├── ..data -> ..2024_04_30_09_51_50.1272065217
# │   └── ready -> ..data/ready
# ├── home
# ├── results
# ├── run
# │   └── 0
# │       └── status
# │           └── results
# ├── scripts
# │   └── script-0-grng7
# ├── steps
# │   ├── 0 -> /tekton/run/0/status
# │   └── step-list-files -> /tekton/run/0/status
# └── termination

# 16 directories, 5 files

# + tree -a /workspace
# /workspace
# └── read-allowed

# 2 directories, 0 files

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   annotations:
#     pipeline.tekton.dev/release: d714545
#     tekton.dev/ready: READY
#   creationTimestamp: "2024-04-30T09:51:38Z"
#   labels:
#     app.kubernetes.io/managed-by: tekton-pipelines
#     tekton.dev/taskRun: task-with-workspace-run-pqjfb
#   name: task-with-workspace-run-pqjfb-pod
#   namespace: default
#   ownerReferences:
#     - apiVersion: tekton.dev/v1
#       blockOwnerDeletion: true
#       controller: true
#       kind: TaskRun
#       name: task-with-workspace-run-pqjfb
#       uid: af91f880-a3c9-41c8-8246-5aba3a68fb01
#   resourceVersion: "623054"
#   uid: 440eb4fc-cf9e-443c-92af-2f78f577ebde
# spec:
#   activeDeadlineSeconds: 5400
#   containers:
#     - args:
#         - -wait_file
#         - /tekton/downward/ready
#         - -wait_file_content
#         - -post_file
#         - /tekton/run/0/out
#         - -termination_path
#         - /tekton/termination
#         - -step_metadata_dir
#         - /tekton/run/0/status
#         - -entrypoint
#         - /tekton/scripts/script-0-grng7
#         - --
#       command:
#         - /tekton/bin/entrypoint
#       image: alpine
#       imagePullPolicy: Always
#       name: step-list-files
#       resources: {}
#       terminationMessagePath: /tekton/termination
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /workspace/read-allowed
#           name: ws-cfpgv
#         - mountPath: /tekton/scripts
#           name: tekton-internal-scripts
#           readOnly: true
#         - mountPath: /tekton/downward
#           name: tekton-internal-downward
#           readOnly: true
#         - mountPath: /tekton/creds
#           name: tekton-creds-init-home-0
#         - mountPath: /tekton/run/0
#           name: tekton-internal-run-0
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#           readOnly: true
#         - mountPath: /workspace
#           name: tekton-internal-workspace
#         - mountPath: /tekton/home
#           name: tekton-internal-home
#         - mountPath: /tekton/results
#           name: tekton-internal-results
#         - mountPath: /tekton/steps
#           name: tekton-internal-steps
#           readOnly: true
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-dcbq5
#           readOnly: true
#   dnsPolicy: ClusterFirst
#   enableServiceLinks: true
#   initContainers:
#     - command:
#         - /ko-app/entrypoint
#         - init
#         - /ko-app/entrypoint
#         - /tekton/bin/entrypoint
#         - step-list-files
#       image: ghcr.io/lanzhiwang/tekton-releases/tektoncd/pipeline/cmd/entrypoint:v0.57.0
#       imagePullPolicy: IfNotPresent
#       name: prepare
#       resources: {}
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#         - mountPath: /tekton/steps
#           name: tekton-internal-steps
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-dcbq5
#           readOnly: true
#       workingDir: /
#     - args:
#         - -c
#         - |
#           scriptfile="/tekton/scripts/script-0-grng7"
#           touch ${scriptfile} && chmod +x ${scriptfile}
#           cat > ${scriptfile} << '_EOF_'
#           IyEvYmluL3NoCnNldCAtZQpzZXQgLXgKYXBrIGFkZCB0cmVlCnRyZWUgLWEgL3Rla3Rvbgp0cmVlIC1hIC93b3Jrc3BhY2UKbHMgL3dvcmtzcGFjZS9yZWFkLWFsbG93ZWQKdHJlZSAtYSAvdGVrdG9uCnRyZWUgLWEgL3dvcmtzcGFjZQo=
#           _EOF_
#           /tekton/bin/entrypoint decode-script "${scriptfile}"
#       command:
#         - sh
#       image: ghcr.io/lanzhiwang/chainguard/busybox:v1.0.0
#       imagePullPolicy: IfNotPresent
#       name: place-scripts
#       resources: {}
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /tekton/scripts
#           name: tekton-internal-scripts
#         - mountPath: /tekton/bin
#           name: tekton-internal-bin
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-dcbq5
#           readOnly: true
#   nodeName: 192.168.137.27
#   preemptionPolicy: PreemptLowerPriority
#   priority: 0
#   restartPolicy: Never
#   schedulerName: default-scheduler
#   securityContext: {}
#   serviceAccount: default
#   serviceAccountName: default
#   terminationGracePeriodSeconds: 30
#   tolerations:
#     - effect: NoExecute
#       key: node.kubernetes.io/not-ready
#       operator: Exists
#       tolerationSeconds: 30
#     - effect: NoExecute
#       key: node.kubernetes.io/unreachable
#       operator: Exists
#       tolerationSeconds: 30
#   volumes:
#     - emptyDir: {}
#       name: tekton-internal-workspace
#     - emptyDir: {}
#       name: tekton-internal-home
#     - emptyDir: {}
#       name: tekton-internal-results
#     - emptyDir: {}
#       name: tekton-internal-steps
#     - emptyDir: {}
#       name: tekton-internal-scripts
#     - emptyDir: {}
#       name: tekton-internal-bin
#     - downwardAPI:
#         defaultMode: 420
#         items:
#           - fieldRef:
#               apiVersion: v1
#               fieldPath: metadata.annotations['tekton.dev/ready']
#             path: ready
#       name: tekton-internal-downward
#     - emptyDir:
#         medium: Memory
#       name: tekton-creds-init-home-0
#     - emptyDir: {}
#       name: tekton-internal-run-0
#     - name: ws-cfpgv
#       persistentVolumeClaim:
#         claimName: pvc-234e862f98
#     - name: kube-api-access-dcbq5
#       projected:
#         defaultMode: 420
#         sources:
#           - serviceAccountToken:
#               expirationSeconds: 3607
#               path: token
#           - configMap:
#               items:
#                 - key: ca.crt
#                   path: ca.crt
#               name: kube-root-ca.crt
#           - downwardAPI:
#               items:
#                 - fieldRef:
#                     apiVersion: v1
#                     fieldPath: metadata.namespace
#                   path: namespace
